pring:
  application:
    name: alunosapi
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/alunos-api
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
#    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
logging:
  level:
    feign: debug
    hibernate: error
